### ISSUE TITLE
mautrix-whatsapp has been broken since 1.10

### ISSUE THREAD

**Issue by bugzy** [amanning9/copr-matrix#1]
Just wondering if you have the time to fix the mautrix-whatsapp specfile so that newer versions are packaged.

**Comment by amanning9** [comment]
The builds for rawhide and fedora 36 have been working, so since it's a go application with all it's dependencies bundled you can `sudo dnf update --releasever rawhide mautrix-whatsapp` to get the most recent build!

**Comment by bugzy** [comment]
Great. sudo dnf update --releasever 36 mautrix-whatsapp  is what worked for me. thanks
